function [Cvb]=Calculate_Cbv(phi,theta,psi)
    C1v=[cos(psi),sin(psi),0;...
         -sin(psi),cos(psi),0;...
         0,0,1];
    C21=[cos(theta),0,-sin(theta);...
         0,1,0;...
         sin(theta),0,cos(theta)];
    Cb2=[1,0,0;...
         0,cos(phi),sin(phi);...
         0,-sin(phi),cos(phi)];
    Cbv=Cb2*C21*C1v;
    Cvb=inv(Cbv);
end